name: Teste frontend

defaults:
  run:
    working-directory: "frontend/"

on:
  workflow_dispatch:
  push:
    branches:
    - frontend
    paths:
    - 'frontend/**'

jobs:
  Teste:
    name: Teste frontend
    runs-on: self-hosted

    steps:

      - name: Getting dependencies
        run: |
          cd app/
          apt-get update && apt-get -y install npm
          npm install -g @angular/cli

      - name: Test execution
        run: |
          ng test
