name: Teste frontend

defaults:
  run:
    working-directory: "frontend/app"

on:
  workflow_dispatch:
  push:
    branches:
    - frontend
    paths:
    - '.github/workflows/frontend-ci.yml'

env:
  USER: ${{ github.actor }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  REGISTRY: ghcr.io

jobs:
  Teste:
    name: Teste frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up nodejs 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'
        
      - name: Install angular cli
        run: npm install -g @angular/cli

      - name: Run test
        run: ng test

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USER }}
          password: ${{ env.GH_TOKEN }}

      - name: Build Backend Dockerfile
        run: docker build . --tag frontend-app:latest

      - name: Tag Backend Docker image
        run: docker tag frontend-app:latest ${{ env.REGISTRY }}/${{ env.USER }}/frontend-app:latest

      - name: Push Backend Docker image
        run:  docker push ${{ env.REGISTRY }}/${{ env.USER }}/frontend-app:latest

